=== ivanvykopal/VAVA-Project/Skladový systém/src/warehouse.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Pre kontrolu správnosti formátu XML súboru vložte nasledujúci riadok do xml súboru:
        <!DOCTYPE warehouse SYSTEM "warehouse.dtd"> 
-->

<!ELEMENT warehouse (goods)*>
<!ELEMENT goods (name, code, description, prices, deleted)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT prices (incomePrice, exportPrice)>
<!ELEMENT deleted (#PCDATA)>
<!ELEMENT incomePrice (#PCDATA)>
<!ELEMENT exportPrice (#PCDATA)>

=== ivanvykopal/VAVA-Project/Skladový systém/src/goods.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE warehouse SYSTEM "warehouse.dtd">

<warehouse>
    <goods>
        <name>Matica 16</name>
        <code>M-16</code>
        <description>Matica o veľkosti 16</description>
        <prices>
            <incomePrice>0.02</incomePrice>
            <exportPrice>0.03</exportPrice>
        </prices>
        <deleted>false</deleted>
    </goods>
    <goods>
        <name>Matica 18</name>
        <code>M-18</code>
        <description>Matica s veľkostťou 18</description>
        <prices>
            <incomePrice>0.03</incomePrice>
            <exportPrice>0.04</exportPrice>
        </prices>
        <deleted>false</deleted>
    </goods>
    <goods>
        <name>Skrutka</name>
        <code>S-M3</code>
        <description>Skrutka; M3x10;</description>
        <prices>
            <incomePrice>0.01</incomePrice>
            <exportPrice>0.02</exportPrice>
        </prices>
        <deleted>false</deleted>
    </goods>
</warehouse>
